
name: "Docker publish"

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      generic_tag:
        required: true
        type: string

jobs:
  deploy-ghcr:
    permissions:
      packages: write
    uses: ./.github/workflows/publish_ghcr.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      generic_tag: ${{ inputs.generic_tag }}

  deploy-dockerhub:
    uses: ./.github/workflows/publish_dockerhub.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      generic_tag: ${{ inputs.generic_tag }}

  deploy-ecr:
    uses: ./.github/workflows/publish_ecr.yml
    permissions:
      contents: read # To read secrets
      id-token: write # This is required for requesting the JWT
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      generic_tag: ${{ inputs.generic_tag }}
