
name: "Docker publish"

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      generic_tag:
        required: true
        type: string        
jobs:

  # load-image:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download docker image
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: image
  #         path: /tmp

  #     # setup containerd to preserve provenance attestations :https://docs.docker.com/build/attestations/#creating-attestations
  #     - name: Setup docker with containerd
  #       uses: crazy-max/ghaction-setup-docker@v3
  #       with:
  #         daemon-config: |
  #           {
  #             "features": {
  #               "containerd-snapshotter": true
  #             }
  #           }     
                      
  #     - name: Load docker image into daemon
  #       run: |
  #         docker load --input /tmp/image.tar

  deploy-ghcr:
    permissions:
      packages: write
    uses: ./.github/workflows/publish_ghcr.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      generic_tag: ${{ inputs.generic_tag }}

  deploy-dockerhub:
    uses: ./.github/workflows/publish_dockerhub.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      generic_tag: ${{ inputs.generic_tag }}

  deploy-ecr:
    uses: ./.github/workflows/publish_ecr.yml
    permissions:
      contents: read # To read secrets
      id-token: write # This is required for requesting the JWT
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      generic_tag: ${{ inputs.generic_tag }}