
name: "Docker GHCR publish"

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      generic_tag:
        required: true
        type: string

jobs:
  deploy-ghcr:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Download docker image
        uses: actions/download-artifact@v4
        with:
          name: image
          path: /tmp

      - name: Load docker image into daemon
        run: |
          docker load --input /tmp/image.tar

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images to GHCR
        run: |
          # docker tag kafka-ui:temp ghcr.io/kafbat/kafka-ui:${{ inputs.generic_tag }}
          # docker tag kafka-ui:temp ghcr.io/kafbat/kafka-ui:${{ inputs.version }}
          # docker push ghcr.io/kafbat/kafka-ui:${{ inputs.generic_tag }}
          # docker push ghcr.io/kafbat/kafka-ui:${{ inputs.version }}
          docker tag kafka-ui:temp ghcr.io/giom-l/kafka-ui:${{ inputs.generic_tag }}
          docker tag kafka-ui:temp ghcr.io/giom-l/kafka-ui:${{ inputs.version }}
          docker push ghcr.io/giom-l/kafka-ui:${{ inputs.generic_tag }}
          docker push ghcr.io/giom-l/kafka-ui:${{ inputs.version }}

