name: "Main save/load : Build & deploy"
on:
  workflow_dispatch:

  push:
    branches: [ "feat/improve_docker_publish" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    outputs: 
      version: ${{ steps.build.outputs.version }}  

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ github.token }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'maven'

      - name: Build a jar
        id: build
        run: |
          ./mvnw -B -ntp versions:set -DnewVersion=$GITHUB_SHA
          ./mvnw -V -B -ntp clean package -Pprod -DskipTests
          export VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build multi platform images and loading them at the same time is not possible with default container runtime : https://github.com/docker/buildx/issues/59   
      # So let's use containerd instead as it supports this option
      # Also containerd is one of the option to allow preserving provenance attestations :https://docs.docker.com/build/attestations/#creating-attestations
      - name: Setup docker with containerd
        uses: crazy-max/ghaction-setup-docker@v3
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }              

      - name: Build & push 
        id: docker_build_and_push_by_digest
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: api
          platforms: linux/amd64,linux/arm64
          provenance: mode=min
          sbom: true
          push: false
          load: true
          tags: |
            kafka-ui:temp
          build-args: |
            JAR_FILE=api-${{ steps.build.outputs.version }}.jar
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Dump docker image
        run: |
          docker image save kafka-ui:temp > /tmp/image.tar

      - name: Upload docker image
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: /tmp/image.tar
          retention-days: 1

  deploy-ghcr:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write

    steps: 
      - name: Download docker image
        uses: actions/download-artifact@v4
        with:
          name: image
          path: /tmp

      # setup containerd to preserve provenance attestations :https://docs.docker.com/build/attestations/#creating-attestations
      - name: Setup docker with containerd
        uses: crazy-max/ghaction-setup-docker@v3
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }     
                      
      - name: Load docker image into daemon
        run: |
          docker load --input /tmp/image.tar
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images to GHCR
        run: |
          docker tag kafka-ui:temp ghcr.io/giom-l/kafka-ui:main
          docker tag kafka-ui:temp ghcr.io/giom-l/kafka-ui:${{ needs.build.outputs.version }}
          docker push ghcr.io/giom-l/kafka-ui:main
          docker push ghcr.io/giom-l/kafka-ui:${{ needs.build.outputs.version }}

  deploy-dockerhub:
    runs-on: ubuntu-latest
    needs: build

    steps: 
      - name: Download docker image
        uses: actions/download-artifact@v4
        with:
          name: image
          path: /tmp

      # setup containerd to preserve provenance attestations :https://docs.docker.com/build/attestations/#creating-attestations
      - name: Setup docker with containerd
        uses: crazy-max/ghaction-setup-docker@v3
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }     

      - name: Load docker image into daemon
        run: |
          docker load --input /tmp/image.tar

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Push images to dockerhub
        run: |
          docker tag kafka-ui:temp docker.io/${{ secrets.DOCKERHUB_USERNAME }}/kafka-ui:main
          docker tag kafka-ui:temp docker.io/${{ secrets.DOCKERHUB_USERNAME }}/kafka-ui:${{ needs.build.outputs.version }}
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/kafka-ui:main
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/kafka-ui:${{ needs.build.outputs.version }}


  deploy-ecr:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read # To read secrets
      id-token: write # This is required for requesting the JWT

    steps: 
      - name: Download docker image
        uses: actions/download-artifact@v4
        with:
          name: image
          path: /tmp

      # setup containerd to preserve provenance attestations :https://docs.docker.com/build/attestations/#creating-attestations
      - name: Setup docker with containerd
        uses: crazy-max/ghaction-setup-docker@v3
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }     

      - name: Load docker image into daemon
        run: |
          docker load --input /tmp/image.tar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1 # This region only for public ECR
          role-to-assume: ${{ secrets.AWS_ROLE }}

      - name: Login to public ECR
        uses: docker/login-action@v3
        with:
          registry: public.ecr.aws

      - name: Push to ECR
        uses: jwalton/gh-ecr-push@v2
        with:
          local-image: kafka-ui:temp
          image: public.ecr.aws/j4u0y1h1/kafka-ui:main, public.ecr.aws/j4u0y1h1/kafka-ui:${{ needs.build.outputs.version }}  
      # - name: Push images to ECR
      #   run: |
      #     docker tag kafka-ui:temp public.ecr.aws/j4u0y1h1/kafka-ui:main
      #     docker tag kafka-ui:temp public.ecr.aws/j4u0y1h1/kafka-ui:${{ needs.build.outputs.version }}
      #     docker push public.ecr.aws/j4u0y1h1/kafka-ui:main
      #     docker push public.ecr.aws/j4u0y1h1/kafka-ui:${{ needs.build.outputs.version }}

        