name: "Test Main: Build & deploy"
on:
  workflow_dispatch:

  push:
    branches: [ "feat/improve_docker_publish" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ github.token }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'maven'

      - name: Build a jar
        id: build
        run: |
          ./mvnw -B -ntp versions:set -DnewVersion=$GITHUB_SHA
          ./mvnw -V -B -ntp clean package -Pprod -DskipTests
          export VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      # docker images

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Build multi platform images and loading them at the same time is not possible with default container runtime : https://github.com/docker/buildx/issues/59   
      # So let's use containerd instead as it supports this option
      - name: Setup docker with containerd
        uses: crazy-max/ghaction-setup-docker@v3
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }              
            
      # Either we use oci exports and use it in subsequent jobs
      # Or we try to active containerd, load the image after build then dump it into tar file
      - name: Build & push 
        id: docker_build_and_push_by_digest
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: api
          platforms: linux/amd64,linux/arm64
          provenance: true
          push: false
          load: true
          tags: |
            kafka-ui:latest
          #   ghcr.io/giom-l/kafka-ui:${{ steps.build.outputs.version }}
          #   ghcr.io/giom-l/kafka-ui:main
          #   gocho/kafka-ui:${{ steps.build.outputs.version }}
          #   gocho/kafka-ui:main            
          build-args: |
            JAR_FILE=api-${{ steps.build.outputs.version }}.jar
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          outputs: type=oci,dest=/tmp/image.tar

      - name: debug
        run: |
          docker images 
          ls -la /tmp

      - name: Dump docker image
        run: |
          docker image save kafka-ui:latest > /tmp/imagedump.tar
  

      - name: Upload docker image
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: /tmp/image.tar
          retention-days: 1

      - name: Upload docker image
        uses: actions/upload-artifact@v4
        with:
          name: imagedump
          path: /tmp/imagedump.tar
          retention-days: 1

  deploy-ghcr:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write

    steps: 
      # - name: Checkout
      #   uses: actions/checkout@v4
      #   with:
      #     ref: ${{ github.event.pull_request.head.sha }}
      #     token: ${{ github.token }}

      - name: Download docker image
        uses: actions/download-artifact@v4
        with:
          name: image
          path: /tmp


      - name: Download docker imagedump
        uses: actions/download-artifact@v4
        with:
          name: imagedump
          path: /tmp

      # Due to https://github.com/docker/buildx/issues/1553
      - name: Manually unpack the tar
        run: |
          mkdir -p /tmp/kafka-ui && tar -C /tmp/kafka-ui -xf /tmp/image.tar
          ls -laRH /tmp/kafka-ui
          mkdir -p /tmp/kafka-ui-dump && tar -C /tmp/kafka-ui-dump -xf /tmp/imagedump.tar
      # - name: Load Docker image
      #   run: |
      #     docker load --input /tmp/image.tar
      #     docker ps -a
      #     docker images
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "giom-l"
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Tag for registry and push
      #   run: |
      #     docker tag kafka-ui:latest ghcr.io/giom-l/kafka-ui:${{ steps.build.outputs.version }}
      #     docker tag kafka-ui:latest ghcr.io/giom-l/kafka-ui:main
      #     docker push ghcr.io/giom-l/kafka-ui:${{ steps.build.outputs.version }}
      #     docker push ghcr.io/giom-l/kafka-ui:main
      # - name: Login to Dockerhub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build multi platform images and loading them at the same time is not possible with default container runtime : https://github.com/docker/buildx/issues/59   
      # So let's use containerd instead as it supports this option
      - name: Setup docker with containerd
        uses: crazy-max/ghaction-setup-docker@v3
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }              


      # with containerd way
      - name: Set up containerd
        uses: crazy-max/ghaction-setup-containerd@v2       

      - name: Import image in containerd
        run: |
          sudo ctr i import --base-name kafka-ui --digests --all-platforms /tmp/image.tar
      
      - name: Push images to GHCR
        run: |
          sudo ctr image tag docker.io/library/kafka-ui:latest ghcr.io/giom-l/kafka-ui:main
          sudo ctr image tag docker.io/library/kafka-ui:latest ghcr.io/giom-l/kafka-ui:latest
          sudo ctr image push ghcr.io/giom-l/kafka-ui:main
          sudo ctr image push ghcr.io/giom-l/kafka-ui:latest

      - name: load image in docker
        if: success() || failure()
        run: | 
          docker load --input /tmp/imagedump.tar
          docker images
          docker tag kafka-ui:latest ghcr.io/giom-l/kafka-ui:main3
          docker push ghcr.io/giom-l/kafka-ui:main3     
      - name: Build & push docker image
        if: success() || failure()
        id: docker_build_and_push
        uses: docker/build-push-action@v5
        with:
          # builder: ${{ steps.buildx.outputs.name }}
          # context: api
          context: /tmp/kafka-ui-dump
          platforms: linux/amd64,linux/arm64
          provenance: true
          load: true
          push: true
          tags: |
            ghcr.io/giom-l/kafka-ui:main2
            ghcr.io/giom-l/kafka-ui:latest2
